### ISSUE TITLE
[Qtile] Key value pairs missing from config.json

### ISSUE THREAD

**Issue by fabestah** [dani-lp/dotfiles#2]
I think I've encountered a bug regarding the config.json file that gets created when running your config although I could also have done something wrong as I'm relatively new to Python.

The thing is, Qtile doesn't find certain key value pairs from the `config.json` when going through `widgets.py` because they don't get written to the config in `utils` -> `variables.py`. As a matter of fact only the variables specified in `variables.py` get written to the config.

Could it be that you made a mistake when you restructured the config and didn't notice it because for you the file doesn't get rewritten as you still have the old working `config.json` 🤔

Missing items from the config:
- "with_battery"
- "with_wlan"
- "two_monitors"
- "wallpaper_main" and "wallpaper_sec" instead of just "wallpaper"

**Comment by dani-lp** [comment]
Nice catch, thanks! It's fixed now.

**Comment by fabestah** [comment]
I don't know if you took that fix from my fork but if so, I only created a temporary fix for it and it's not particularly the best solution.
After looking more into it, the real problem is that the `base-config` doesn't actually get used / read in `variables.py` which I guess was the main config file before you restructured. Instead a new `config.json` gets created with only the variables defined in `variables.py` and not with all the variables defined in `settings.py` or the `base-config.json` (I'm not really sure which file you intended to use as a place to define all of the settings because there is some stuff in `settings.py` which isn't stated elsewhere (e.g. workspace names).

Therefore I will restructure things in my fork so, that everything will be configurable in one `config.json` (terminal, with_wlan, workspace_names, colors, etc.) but split the variables up into different dictionaries for the various use cases in the specific files.
Then the workspaces_names and colors can be imported from `variables.py` and also get configured in a clearer and simpler way over the `config.json` in main Qtile config directory without having to dig that much into the config (`settings.py` will be redundant then).
And the other variables can get used inside the config files exactly the same way as before but without the need of an unnecessary `base-config.json` and they also can be accessed from the user in a simpler way without having to dig into the config (`variables.py`).
By doing this I also will rename the .json file into `settings.json`

If you also want to have it working like that in your Qtile config, I can open a PR after I'm done (if you want to keep the name of the `config.json` just tell me)? :)

**Comment by dani-lp** [comment]
Hi again! Sorry for the late reply.

The idea behind `base-config.json` was originally to copy the values into a `config.json` (which is ignored in `.gitignore`), similarly to how some projects provide a `.env.sample` that needs to be copied into a `.env` file. I didn't think much about that decision, and I now think that it doesn't make much sense to follow that model.

Feel free to open a PR, using `settings.json` is fine!

**Comment by fabestah** [comment]
Not problem at all, I'm not in a hurry! :D

Ah okay, unfortunately, I don't know much about `.env.sample` as I don't code for that long and therefore didn't learn much about envs yet besides using them but it makes sense to throw that model overboard then.
What benefits would that model have provided to specifying the config values? (if you want to explain)

Great, I will do that then but it might take some time as I just re-setup Windows and Arch, just so you know :)
