### ISSUE TITLE
Jpg background image error

### ISSUE THREAD

**Issue by kaiozwald** [dani-lp/dotfiles#4]
Hi, so first of all thanks for the well defined dots, i faced problem setting background from variables.py, if the image was .png it is set successfully, but if it is jpg what happens is when i reload the config the background start to contrast or like have alot of light effects that cause bad image, also if i tried to set .jpg  then replace it with .jpg the image will be like we put the 2 on each others,
i don't know if this problem is because of qtile, or wayland (i use qtile wayland) or what,
so if you can help me define the problem and see what is the cause i'll be thankful 
Drive for images for better idea:
https://drive.google.com/drive/folders/1MDR5jHRllQ8snHJvIHHO9QCP9cOTUcyE?usp=sharing

**Comment by dani-lp** [comment]
Hey there, I'm pretty sure this is a Wayland issue. I've always run X11, and used `.jpg` and `.png` without issues.

The kind of bug in your screenshots doesn't look like anything I've seen Qtile-related. I believe on X11 a compositor might cause these issues, but I'm not familiar with how Wayland works with compositors.

**Comment by kaiozwald** [comment]
thanks for answer
